# -*- coding: utf-8 -*-
"""COVID_May.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FfAZUrkBYqXJH4tnZLu8o88JioEY9VLe
"""

!pip install chart_studio

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
# %matplotlib inline 
import matplotlib.pyplot as plt
from numpy import array
from numpy import argmax
import seaborn as sns
import plotly.graph_objects as go
import plotly.express as px
import plotly.io as pio
import chart_studio
import requests
from datetime import datetime

raw= requests.get("https://services1.arcgis.com/0MSEUqKaxRlEPj5g/arcgis/rest/services/Coronavirus_2019_nCoV_Cases/FeatureServer/1/query?where=1%3D1&outFields=*&outSR=4326&f=json")
raw_json = raw.json()
df = pd.DataFrame(raw_json["features"])

df.tail()

df["attributes"][0]

data_list = df["attributes"].tolist()
df_final = pd.DataFrame(data_list)
df_final.set_index("OBJECTID")
df_final = df_final[["Country_Region", "Province_State", "Lat", "Long_", "Confirmed", "Deaths", "Recovered", "Last_Update"]]
df_final.head()

def convertTime(t):
    t = int(t)
    return datetime.fromtimestamp(t)

df_final = df_final.dropna(subset=["Last_Update"])
df_final["Province_State"].fillna(value="", inplace=True)

df_final["Last_Update"]= df_final["Last_Update"]/1000
df_final["Last_Update"] = df_final["Last_Update"].apply(convertTime)

df_final.head()

df_final = df_final[ (df_final['Country_Region'] == 'Ghana') | (df_final['Country_Region'] == "Nigeria") |
(df_final['Country_Region'] == "Senegal")| (df_final['Country_Region'] == "Gambia")| (df_final['Country_Region'] == "Benin")|
(df_final['Country_Region'] == "Togo")|(df_final['Country_Region'] == "Burkina Faso")|(df_final['Country_Region'] == "Cote d'Ivoire")|
(df_final['Country_Region'] == "Liberia")|(df_final['Country_Region'] == "Guinea")|(df_final['Country_Region'] == "Niger")|
(df_final['Country_Region'] == "Mali")|(df_final['Country_Region'] == "Guinea-Bissau")|(df_final['Country_Region'] == "South Africa")|
(df_final['Country_Region'] == "Algeria")|(df_final['Country_Region'] == "Angola")|(df_final['Country_Region'] == "Botswana")
|(df_final['Country_Region'] == "Burundi")|(df_final['Country_Region'] == "Cabo Verde")|(df_final['Country_Region'] == "Cameroon")
|(df_final['Country_Region'] == "Central African Republic")|(df_final['Country_Region'] == "Chad")|(df_final['Country_Region'] == "Comoros")
|(df_final['Country_Region'] == "Congo (Kinshasa)")|(df_final['Country_Region'] == "Congo (Brazzaville)")|
(df_final['Country_Region'] == "Djibouti")|(df_final['Country_Region'] == "Rwanda")|(df_final['Country_Region'] == "Sao Tome and Principe")
|(df_final['Country_Region'] == "Egypt")|(df_final['Country_Region'] == "Mauritania")|(df_final['Country_Region'] == "Malawi")
|(df_final['Country_Region'] == "Equatorial Guinea")|(df_final['Country_Region'] == "Mauritius")|(df_final['Country_Region'] == "Madagascar")
|(df_final['Country_Region'] == "Eritrea")|(df_final['Country_Region'] == "Morocco")|(df_final['Country_Region'] == "Libya")
|(df_final['Country_Region'] == "Eswatini")|(df_final['Country_Region'] == "Mozambique")|(df_final['Country_Region'] == "Lesotho")
|(df_final['Country_Region'] == "Ethiopia")|(df_final['Country_Region'] == "Namibia")|(df_final['Country_Region'] == "Kenya")
|(df_final['Country_Region'] == "Seychelles")|(df_final['Country_Region'] == "Somalia")|(df_final['Country_Region'] == "South Sudan")
|(df_final['Country_Region'] == "Sudan")|(df_final['Country_Region'] == "Tanzania")|(df_final['Country_Region'] == "Tunisia")
|(df_final['Country_Region'] == "Uganda")|(df_final['Country_Region'] == "Zambia")|(df_final['Country_Region'] == "Zimbabwe")
|(df_final['Country_Region'] == "Gabon")

]
df_final.reset_index(drop=True, inplace=True)
df_final.head()

df_final = df_final.drop(['Province_State'], axis=1)
df_final.head()

df_total = df_final.groupby("Country_Region", as_index=False).agg(
    {
        "Confirmed" : "sum",
        "Deaths" : "sum",
        "Recovered" : "sum"
    }
)

df_total.head()

total_confirmed = df_final["Confirmed"].sum()
total_recovered = df_final["Recovered"].sum()
total_deaths = df_final["Deaths"].sum()

df_top10 = df_total.nlargest(10, "Confirmed")
top10_countries_1 = df_top10["Country_Region"].tolist()
top10_confirmed = df_top10["Confirmed"].tolist()

df_top10 = df_total.nlargest(10, "Recovered")
top10_countries_2 = df_top10["Country_Region"].tolist()
top10_recovered = df_top10["Recovered"].tolist()

df_top10 = df_total.nlargest(10, "Deaths")
top10_countries_3 = df_top10["Country_Region"].tolist()
top10_deaths = df_top10["Deaths"].tolist()

from plotly.subplots import make_subplots
fig = make_subplots(
    rows = 4, cols = 6,
    specs=[
            [{"type": "scattergeo", "rowspan": 4, "colspan": 3}, None, None, {"type": "indicator"}, {"type": "indicator"}, {"type": "indicator"} ],
            [    None, None, None,               {"type": "bar", "colspan":3}, None, None],
            [    None, None, None,              {"type": "bar", "colspan":3}, None, None],
            [    None, None, None,               {"type": "bar", "colspan":3}, None, None],
          ]
)

fig = make_subplots(
    rows = 4, cols = 6,

    specs=[
            [{"type": "scattergeo", "rowspan": 4, "colspan": 3}, None, None, {"type": "indicator"}, {"type": "indicator"}, {"type": "indicator"} ],
            [    None, None, None,               {"type": "bar", "colspan":3}, None, None],
            [    None, None, None,              {"type": "bar", "colspan":3}, None, None],
            [    None, None, None,               {"type": "bar", "colspan":3}, None, None],
          ]
)


message = df_final["Country_Region"] + " " + "<br>"
message += "Confirmed: " + df_final["Confirmed"].astype(str) + "<br>"
message += "Deaths: " + df_final["Deaths"].astype(str) + "<br>"
message += "Recovered: " + df_final["Recovered"].astype(str) + "<br>"
message += "Last updated: " + df_final["Last_Update"].astype(str)
df_final["text"] = message

fig.add_trace(
    go.Scattergeo(
        locationmode = "country names",
        lon = df_final["Long_"],
        lat = df_final["Lat"],
        hovertext = df_final["text"],
        showlegend=False,
        marker = dict(
            size = 10,
            opacity = 0.8,
            reversescale = True,
            autocolorscale = True,
            symbol = 'square',
            line = dict(
                width=1,
                color='rgba(102, 102, 102)'
            ),
            cmin = 0,
            color = df_final['Confirmed'],
            cmax = df_final['Confirmed'].max(),
            colorbar_title="Confirmed Cases<br>Latest Update",  
            colorbar_x = -0.05
        )

    ),
    
    row=1, col=1
)

fig.add_trace(
    go.Indicator(
        mode="number",
        value=total_confirmed,
        title="Confirmed Cases",
    ),
    row=1, col=4
)

fig.add_trace(
    go.Indicator(
        mode="number",
        value=total_recovered,
        title="Recovered Cases",
    ),
    row=1, col=5
)

fig.add_trace(
    go.Indicator(
        mode="number",
        value=total_deaths,
        title="Deaths Cases",
    ),
    row=1, col=6
)

fig.add_trace(
    go.Bar(
        x=top10_countries_1,
        y=top10_confirmed, 
        name= "Confirmed Cases",
        marker=dict(color="Yellow"), 
        showlegend=True,
    ),
    row=2, col=4
)

fig.add_trace(
    go.Bar(
        x=top10_countries_2,
        y=top10_recovered, 
        name= "Recovered Cases",
        marker=dict(color="Green"), 
        showlegend=True),
    row=3, col=4
)

fig.add_trace(
    go.Bar(
        x=top10_countries_3,
        y=top10_deaths, 
        name= "Deaths Cases",
        marker=dict(color="crimson"), 
        showlegend=True),
    row=4, col=4
)


fig.update_layout(
    template="plotly_dark",
    title = "Africa COVID-19 Cases (Last Updated: " + str(df_final["Last_Update"][0]) + ")",
    showlegend=True,
    legend_orientation="h",
    legend=dict(x=0.65, y=0.8),
    geo = dict(
            projection_type="orthographic",
            showcoastlines=True,
            landcolor="white", 
            showland= True,
            showocean = True,
            lakecolor="LightBlue"
    ),

    annotations=[
        dict(
            text="Source: https://bit.ly/2SVkufR",
            showarrow=False,
            xref="paper",
            yref="paper",
            x=0.35,
            y=0)
    ]
)

fig.show()
#fig.write_html('first_figure.html', auto_open=True)

fig17 = px.choropleth(df_final, locations="Country_Region", 
                    locationmode='country names', color="Deaths", 
                    hover_name="Country_Region", range_color=[1,200], 
                    color_continuous_scale='portland',
                    title='Deaths in Africa', scope='africa', height=800, width=800)
fig17.update_layout(
    title="Deaths in Africa ",
    xaxis_title="Date",
    yaxis_title="Infected",
    coloraxis_showscale=False
    #autosize=True
)
fig17.show()

fig17 = px.choropleth(df_final, locations="Country_Region", 
                    locationmode='country names', color="Confirmed", 
                    hover_name="Country_Region", range_color=[1,1000], 
                    color_continuous_scale='portland',
                    title='Confirmed cases in Africa', scope='africa', height=800, width=800)
fig17.update_layout(
    title="Confirmed cases in West Africa ",
    xaxis_title="Date",
    yaxis_title="Infected",
    coloraxis_showscale=True
    #autosize=True
)
fig17.show()

fig17 = px.choropleth(df_final, locations="Country_Region", 
                    locationmode='country names', color="Recovered", 
                    hover_name="Country_Region", range_color=[200,1], 
                    color_continuous_scale='portland',
                    title='Recovered cases in West Africa', scope='africa', height=800, width=800)
fig17.update_layout(
    title="Recovered in Africa ",
    xaxis_title="Date",
    yaxis_title="Infected",
    coloraxis_showscale=False
    #autosize=True
)
fig17.show()

df_final.head(115)